<?php

/**
 * WL Assets
 *
 * WARNING: This file is part of the WL Base theme. DO NOT edit this file
 * under any circumstances, as the changes will be lost in the case of a theme update.
 * Please do all modifications in the form of a child theme.
 *
 * @since   1.0.0
 * @package WL\Theme\Base
 * @author  WidgiLabs
 * @license GPL-2.0+
 * @link    http://widgilabs.com/
 */

namespace WL\Theme;

/**
 * Theme assets.
 *
 * @since  1.0.0
 * @author WidgiLabs <dev@widgilabs.com>
 */
class Blocks {




	/**
	 * Setup hooks.
	 *
	 * @since 1.0.0
	 */
	public function ready() {
		if ( function_exists( 'acf_register_block_type' ) ) {
			add_action( 'widgets_init', array( $this, 'register_blocks' ) );
		}
	}

	function register_blocks() {
		acf_register_block_type(
			array(
				'name'            => 'cicles-primary',
				'title'           => __( 'Cicles Primary' ),
				'description'     => __( 'A custom cicles-primary block.' ),
				'render_template' => 'template-parts/blocks/cicles-primary.php',
				'category'        => 'formatting',
			)
		);

		acf_register_block_type(
			array(
				'name'            => 'cicles-text',
				'title'           => __( 'Cicles Text' ),
				'description'     => __( 'A custom cicles-text block.' ),
				'render_template' => 'template-parts/blocks/cicles-text.php',
				'category'        => 'formatting',
			)
		);

		acf_register_block_type(
			array(
				'name'            => 'cicles-know',
				'title'           => __( 'Cicles Know' ),
				'description'     => __( 'A custom cicles-know block.' ),
				'render_template' => 'template-parts/blocks/cicles-know.php',
				'category'        => 'formatting',
			)
		);

		acf_register_block_type(
			array(
				'name'            => 'cicles-content',
				'title'           => __( 'Cicles Content' ),
				'description'     => __( 'A custom cicles-content block.' ),
				'render_template' => 'template-parts/blocks/cicles-content.php',
				'category'        => 'formatting',
			)
		);

		acf_register_block_type(
			array(
				'name'            => 'fale-conosco',
				'title'           => __( 'Fale Conosco' ),
				'description'     => __( 'A custom fale-conosco block.' ),
				'render_template' => 'template-parts/blocks/fale-conosco.php',
				'category'        => 'formatting',
			)
		);

		acf_register_block_type(
			array(
				'name'            => 'mobile-midia',
				'title'           => __( 'Mobile na mídia' ),
				'description'     => __( 'A custom mobile-midia block.' ),
				'render_template' => 'template-parts/blocks/mobile-midia.php',
				'category'        => 'formatting',
			)
		);

		acf_register_block_type(
			array(
				'name'            => 'cookies',
				'title'           => __( 'Cookies' ),
				'description'     => __( 'A custom cookies block.' ),
				'render_template' => 'template-parts/blocks/cookies.php',
				'category'        => 'formatting',
			)
		);

		acf_register_block_type(
			array(
				'name'            => 'double-columns',
				'title'           => __( 'Double Columns' ),
				'description'     => __( 'A custom double-columns block.' ),
				'render_template' => 'template-parts/blocks/double-columns.php',
				'category'        => 'formatting',
			)
		);

		acf_register_block_type(
			array(
				'name'            => 'horizontal-image',
				'title'           => __( 'Horizontal image' ),
				'description'     => __( 'A custom horizontal-image block.' ),
				'render_template' => 'template-parts/blocks/horizontal-image.php',
				'category'        => 'formatting',
			)
		);
	}
}
