<?php
/**
 * WL Images.
 *
 * Use this class to add image related functionality. If not needed please remove, don't forget to update
 * functions.php accordingly
 *
 * WARNING: This file is part of the WL Base theme. DO NOT edit this file
 * under any circumstances, as the changes will be lost in the case of a theme update.
 * Please do all modifications in the form of a child theme.
 *
 * @since   1.0.0
 * @package WL\Theme\Base
 * @author  Nucleus
 * @license GPL-2.0+
 * @link    http://nucleus.eti.br/
 */

namespace WL\Theme;

/**
 * Image related actions.
 *
 * @since  1.0.0
 * @author Nucleus
 */
class Images {


	/**
	 * Adds image sizes.
	 *
	 * @since 1.0.0
	 */
	public function ready() {
		// add_image_size( 'wl_aditional_size', 275, 185, true ); // Ratio: 1.48
	}
}
