<?php
/**
 * wl-base.
 *
 * WARNING: This file is part of the wl-base theme. DO NOT edit this file
 * under any circumstances, as the changes will be lost in the case of a theme update.
 * Please do all modifications in the form of a child theme.
 *
 * @since   1.0.0
 * @package WL
 * @author  Nucleus
 * @license GPL-2.0+
 * @link    http://nucleus.eti.br/
 */

namespace WL\Theme;

/**
 * Theme options.
 *
 * @since  1.0.0
 */
class Options {


	/**
	 * Get theme option.
	 *
	 * @since  1.0.0
	 * @param  string $key     Name of option to retrieve.
	 * @param  mixed  $default Optional. Default value to return if the option does not exist.
	 * @return string          Value set for the option.
	 */
	public static function get_option( $key, $default = false ) {

		if ( empty( $key ) ) {
			return '';
		}

		return get_option( "wl_{$key}", $default );
	}
}
