<?php
/**
 * wl-base.
 *
 * WARNING: This file is part of the wl-base theme. DO NOT edit this file
 * under any circumstances, as the changes will be lost in the case of a theme update.
 * Please do all modifications in the form of a child theme.
 *
 * @since   1.0.0
 * @package wl-base\Templates\Partials
 * @author  Nucleus
 * @license GPL-2.0+
 * @link    http://nucleus.eti.br/
 */

namespace WL\Theme\Templates\Partials;

/**
 * Pagination.
 *
 * @since  1.0.0
 * @author Nucleus
 */
class Pagination {


	/**
	 * Render pagination.
	 *
	 * @since 1.0.0
	 */

	public static function render() {       ?>
		<div class="pagination-container">
			<?php
			the_posts_pagination(
				array(
					'mid_size'           => 1,
					'screen_reader_text' => ' ',
					'prev_text'          => __( 'Prev', 'wl-base' ),
					'next_text'          => __( 'Next', 'wl-base' ),
					'show_all'           => false,
				)
			);
			?>
		</div>
		<?php
	}
}
